package com.hermes.android.ui.theme

import androidx.compose.ui.graphics.Color

// ── Hermes — midnight ink with the messenger's gold (the drawer's HermesAmber) ──

val md_light_primary = Color(0xFF8A6100)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFFBE3A6)
val md_light_onPrimaryContainer = Color(0xFF2B1D00)
val md_light_secondary = Color(0xFF3F5580)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFDCE3F2)
val md_light_onSecondaryContainer = Color(0xFF111C33)
val md_light_tertiary = Color(0xFF1F7A6C)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFCDEFE7)
val md_light_onTertiaryContainer = Color(0xFF00201B)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFF6F4EE)
val md_light_onBackground = Color(0xFF151A26)
val md_light_surface = Color(0xFFFFFDF8)
val md_light_onSurface = Color(0xFF151A26)
val md_light_surfaceVariant = Color(0xFFECE8DC)
val md_light_onSurfaceVariant = Color(0xFF4A4F5C)
val md_light_outline = Color(0xFF7F8494)
val md_light_outlineVariant = Color(0xFFD6D1C4)

val md_dark_primary = Color(0xFFF0B429)
val md_dark_onPrimary = Color(0xFF261A00)
val md_dark_primaryContainer = Color(0xFF4D3A0C)
val md_dark_onPrimaryContainer = Color(0xFFFFE3A3)
val md_dark_secondary = Color(0xFF93A7CB)
val md_dark_onSecondary = Color(0xFF13203A)
val md_dark_secondaryContainer = Color(0xFF243049)
val md_dark_onSecondaryContainer = Color(0xFFDCE5F7)
val md_dark_tertiary = Color(0xFF7FD1C1)
val md_dark_onTertiary = Color(0xFF00302A)
val md_dark_tertiaryContainer = Color(0xFF11443C)
val md_dark_onTertiaryContainer = Color(0xFFB6F2E6)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF0A0E19)
val md_dark_onBackground = Color(0xFFECEFF6)
val md_dark_surface = Color(0xFF111726)
val md_dark_onSurface = Color(0xFFECEFF6)
val md_dark_surfaceVariant = Color(0xFF1A2133)
val md_dark_onSurfaceVariant = Color(0xFFAEB6C8)
val md_dark_outline = Color(0xFF6B7488)
val md_dark_outlineVariant = Color(0xFF2A3346)

// ── آبی چشم (Blue Eye) — low glare for long reading: soft blue-grey, no pure white or black ──

val blue_light_primary = Color(0xFF3B72A0)
val blue_light_onPrimary = Color(0xFFFFFFFF)
val blue_light_primaryContainer = Color(0xFFD3E4F2)
val blue_light_onPrimaryContainer = Color(0xFF0C2A42)
val blue_light_secondary = Color(0xFF4D7587)
val blue_light_onSecondary = Color(0xFFFFFFFF)
val blue_light_secondaryContainer = Color(0xFFD3E5ED)
val blue_light_onSecondaryContainer = Color(0xFF0A2630)
val blue_light_tertiary = Color(0xFF587D6E)
val blue_light_onTertiary = Color(0xFFFFFFFF)
val blue_light_tertiaryContainer = Color(0xFFD6EBE1)
val blue_light_onTertiaryContainer = Color(0xFF112A20)
val blue_light_error = Color(0xFFBA1A1A)
val blue_light_onError = Color(0xFFFFFFFF)
val blue_light_errorContainer = Color(0xFFFFDAD6)
val blue_light_onErrorContainer = Color(0xFF410002)
val blue_light_background = Color(0xFFE8EEF3)
val blue_light_onBackground = Color(0xFF22303D)
val blue_light_surface = Color(0xFFF1F5F9)
val blue_light_onSurface = Color(0xFF22303D)
val blue_light_surfaceVariant = Color(0xFFDAE3EB)
val blue_light_onSurfaceVariant = Color(0xFF4B5A67)
val blue_light_outline = Color(0xFF75838F)
val blue_light_outlineVariant = Color(0xFFC2CEDA)

val blue_dark_primary = Color(0xFF86B6DA)
val blue_dark_onPrimary = Color(0xFF0B2233)
val blue_dark_primaryContainer = Color(0xFF1F3A52)
val blue_dark_onPrimaryContainer = Color(0xFFCFE4F5)
val blue_dark_secondary = Color(0xFF94B4C4)
val blue_dark_onSecondary = Color(0xFF0E2530)
val blue_dark_secondaryContainer = Color(0xFF213540)
val blue_dark_onSecondaryContainer = Color(0xFFD2E6EF)
val blue_dark_tertiary = Color(0xFF9CC4B2)
val blue_dark_onTertiary = Color(0xFF102820)
val blue_dark_tertiaryContainer = Color(0xFF203A31)
val blue_dark_onTertiaryContainer = Color(0xFFD3EDE2)
val blue_dark_error = Color(0xFFFFB4AB)
val blue_dark_onError = Color(0xFF690005)
val blue_dark_errorContainer = Color(0xFF93000A)
val blue_dark_onErrorContainer = Color(0xFFFFDAD6)
val blue_dark_background = Color(0xFF121920)
val blue_dark_onBackground = Color(0xFFD3DCE5)
val blue_dark_surface = Color(0xFF172029)
val blue_dark_onSurface = Color(0xFFD3DCE5)
val blue_dark_surfaceVariant = Color(0xFF1F2A35)
val blue_dark_onSurfaceVariant = Color(0xFF9DACBA)
val blue_dark_outline = Color(0xFF5F7080)
val blue_dark_outlineVariant = Color(0xFF2C3946)

// ── موکا (Mocha) — espresso and caramel after dark, latte cream by day ──

val mocha_light_primary = Color(0xFF8A5A2B)
val mocha_light_onPrimary = Color(0xFFFFFFFF)
val mocha_light_primaryContainer = Color(0xFFF4DBBB)
val mocha_light_onPrimaryContainer = Color(0xFF2E1A05)
val mocha_light_secondary = Color(0xFF7A6352)
val mocha_light_onSecondary = Color(0xFFFFFFFF)
val mocha_light_secondaryContainer = Color(0xFFEADBC9)
val mocha_light_onSecondaryContainer = Color(0xFF2B1E13)
val mocha_light_tertiary = Color(0xFF5E6E3F)
val mocha_light_onTertiary = Color(0xFFFFFFFF)
val mocha_light_tertiaryContainer = Color(0xFFDDE8C4)
val mocha_light_onTertiaryContainer = Color(0xFF1A2308)
val mocha_light_error = Color(0xFFBA1A1A)
val mocha_light_onError = Color(0xFFFFFFFF)
val mocha_light_errorContainer = Color(0xFFFFDAD6)
val mocha_light_onErrorContainer = Color(0xFF410002)
val mocha_light_background = Color(0xFFF4ECE1)
val mocha_light_onBackground = Color(0xFF2A1F17)
val mocha_light_surface = Color(0xFFFFF9F1)
val mocha_light_onSurface = Color(0xFF2A1F17)
val mocha_light_surfaceVariant = Color(0xFFE9DDCD)
val mocha_light_onSurfaceVariant = Color(0xFF5C4E42)
val mocha_light_outline = Color(0xFF8C7D6F)
val mocha_light_outlineVariant = Color(0xFFD5C6B3)

val mocha_dark_primary = Color(0xFFDCA86E)
val mocha_dark_onPrimary = Color(0xFF2B1A06)
val mocha_dark_primaryContainer = Color(0xFF5A3E1F)
val mocha_dark_onPrimaryContainer = Color(0xFFFFDDB5)
val mocha_dark_secondary = Color(0xFFBCA58E)
val mocha_dark_onSecondary = Color(0xFF2A1F15)
val mocha_dark_secondaryContainer = Color(0xFF3A2F26)
val mocha_dark_onSecondaryContainer = Color(0xFFEFDFCC)
val mocha_dark_tertiary = Color(0xFFAABA8B)
val mocha_dark_onTertiary = Color(0xFF1D2609)
val mocha_dark_tertiaryContainer = Color(0xFF34401F)
val mocha_dark_onTertiaryContainer = Color(0xFFDCEBC0)
val mocha_dark_error = Color(0xFFFFB4AB)
val mocha_dark_onError = Color(0xFF690005)
val mocha_dark_errorContainer = Color(0xFF93000A)
val mocha_dark_onErrorContainer = Color(0xFFFFDAD6)
val mocha_dark_background = Color(0xFF16110E)
val mocha_dark_onBackground = Color(0xFFF0E6DA)
val mocha_dark_surface = Color(0xFF1E1814)
val mocha_dark_onSurface = Color(0xFFF0E6DA)
val mocha_dark_surfaceVariant = Color(0xFF29211C)
val mocha_dark_onSurfaceVariant = Color(0xFFC2B3A3)
val mocha_dark_outline = Color(0xFF8A7B6D)
val mocha_dark_outlineVariant = Color(0xFF3D332B)

// ── Midnight — green-black night with an emerald glow ──

val midnight_light_primary = Color(0xFF047857)
val midnight_light_onPrimary = Color(0xFFFFFFFF)
val midnight_light_primaryContainer = Color(0xFFCCEEDF)
val midnight_light_onPrimaryContainer = Color(0xFF002A1B)
val midnight_light_secondary = Color(0xFF4E6B5E)
val midnight_light_onSecondary = Color(0xFFFFFFFF)
val midnight_light_secondaryContainer = Color(0xFFD7E8DF)
val midnight_light_onSecondaryContainer = Color(0xFF0E2119)
val midnight_light_tertiary = Color(0xFF0369A1)
val midnight_light_onTertiary = Color(0xFFFFFFFF)
val midnight_light_tertiaryContainer = Color(0xFFD6EAF6)
val midnight_light_onTertiaryContainer = Color(0xFF002538)
val midnight_light_error = Color(0xFFBA1A1A)
val midnight_light_onError = Color(0xFFFFFFFF)
val midnight_light_errorContainer = Color(0xFFFFDAD6)
val midnight_light_onErrorContainer = Color(0xFF410002)
val midnight_light_background = Color(0xFFEDF3F0)
val midnight_light_onBackground = Color(0xFF13201A)
val midnight_light_surface = Color(0xFFF9FCFA)
val midnight_light_onSurface = Color(0xFF13201A)
val midnight_light_surfaceVariant = Color(0xFFDEE9E3)
val midnight_light_onSurfaceVariant = Color(0xFF43544B)
val midnight_light_outline = Color(0xFF72847A)
val midnight_light_outlineVariant = Color(0xFFC4D4CB)

val midnight_dark_primary = Color(0xFF34D399)
val midnight_dark_onPrimary = Color(0xFF00281A)
val midnight_dark_primaryContainer = Color(0xFF0F4D36)
val midnight_dark_onPrimaryContainer = Color(0xFFA7F3D0)
val midnight_dark_secondary = Color(0xFF8FB3A3)
val midnight_dark_onSecondary = Color(0xFF10251C)
val midnight_dark_secondaryContainer = Color(0xFF1F332B)
val midnight_dark_onSecondaryContainer = Color(0xFFD2E8DD)
val midnight_dark_tertiary = Color(0xFF7DD3FC)
val midnight_dark_onTertiary = Color(0xFF002838)
val midnight_dark_tertiaryContainer = Color(0xFF0B3A52)
val midnight_dark_onTertiaryContainer = Color(0xFFCDEBFA)
val midnight_dark_error = Color(0xFFFFB4AB)
val midnight_dark_onError = Color(0xFF690005)
val midnight_dark_errorContainer = Color(0xFF93000A)
val midnight_dark_onErrorContainer = Color(0xFFFFDAD6)
val midnight_dark_background = Color(0xFF0B1210)
val midnight_dark_onBackground = Color(0xFFE3EEE8)
val midnight_dark_surface = Color(0xFF111A17)
val midnight_dark_onSurface = Color(0xFFE3EEE8)
val midnight_dark_surfaceVariant = Color(0xFF18231E)
val midnight_dark_onSurfaceVariant = Color(0xFFA3B5AC)
val midnight_dark_outline = Color(0xFF62756C)
val midnight_dark_outlineVariant = Color(0xFF26342E)

// ── Manus — measured from the Manus app's dark screenshots: soft charcoal, no colour
// in the chrome. Background #1A1A1A, cards and composer #292929, round buttons #2A2A2A,
// labels #DADADA, secondary text #939393 (Manus #8C8C8C, lifted to pass 4.5:1 on cards).
// Blue only marks a selected or active state,
// as Manus does (#409CF8 on dark; #006FD6 on light, Manus #0081F0 darkened for white text).
// Manus' light mode was not measured; the light palette mirrors the dark one.

val manus_light_primary = Color(0xFF006FD6)
val manus_light_onPrimary = Color(0xFFFFFFFF)
val manus_light_primaryContainer = Color(0xFFDDEEFF)
val manus_light_onPrimaryContainer = Color(0xFF002B52)
val manus_light_secondary = Color(0xFF6B6B6B)
val manus_light_onSecondary = Color(0xFFFFFFFF)
val manus_light_secondaryContainer = Color(0xFFEBEBEB)
val manus_light_onSecondaryContainer = Color(0xFF1A1A1A)
val manus_light_tertiary = Color(0xFF5A6E88)
val manus_light_onTertiary = Color(0xFFFFFFFF)
val manus_light_tertiaryContainer = Color(0xFFE3E9F1)
val manus_light_onTertiaryContainer = Color(0xFF1C2633)
val manus_light_error = Color(0xFFD9363E)
val manus_light_onError = Color(0xFFFFFFFF)
val manus_light_errorContainer = Color(0xFFFFE0E1)
val manus_light_onErrorContainer = Color(0xFF4A0A0D)
val manus_light_background = Color(0xFFF7F7F7)
val manus_light_onBackground = Color(0xFF1A1A1A)
val manus_light_surface = Color(0xFFFFFFFF)
val manus_light_onSurface = Color(0xFF1A1A1A)
val manus_light_surfaceVariant = Color(0xFFEFEFEF)
val manus_light_onSurfaceVariant = Color(0xFF6B6B6B)
val manus_light_outline = Color(0xFF9E9E9E)
val manus_light_outlineVariant = Color(0xFFDDDDDD)

val manus_dark_primary = Color(0xFF409CF8)
val manus_dark_onPrimary = Color(0xFF0A1A2B)
val manus_dark_primaryContainer = Color(0xFF17324D)
val manus_dark_onPrimaryContainer = Color(0xFFD3E8FF)
val manus_dark_secondary = Color(0xFF939393)
val manus_dark_onSecondary = Color(0xFF1A1A1A)
val manus_dark_secondaryContainer = Color(0xFF353535)
val manus_dark_onSecondaryContainer = Color(0xFFDADADA)
val manus_dark_tertiary = Color(0xFF8A9FBA)
val manus_dark_onTertiary = Color(0xFF1A1A1A)
val manus_dark_tertiaryContainer = Color(0xFF2B3440)
val manus_dark_onTertiaryContainer = Color(0xFFDCE6F2)
val manus_dark_error = Color(0xFFF2676C)
val manus_dark_onError = Color(0xFF1A1A1A)
val manus_dark_errorContainer = Color(0xFF4A1C1E)
val manus_dark_onErrorContainer = Color(0xFFFFD9DA)
val manus_dark_background = Color(0xFF1A1A1A)
val manus_dark_onBackground = Color(0xFFDADADA)
val manus_dark_surface = Color(0xFF2A2A2A)
val manus_dark_onSurface = Color(0xFFDADADA)
val manus_dark_surfaceVariant = Color(0xFF292929)
val manus_dark_onSurfaceVariant = Color(0xFF939393)
val manus_dark_outline = Color(0xFF5E5E5E)
val manus_dark_outlineVariant = Color(0xFF333333)
// ── Aether — copied from Aether's own palette (Zhou-Shilin/Aether, ui/theme/Color.kt):
// lavender primary, sage secondary, warm off-white text on blue-grey charcoal.
// Roles Aether leaves to Material's baseline (tertiary/error containers, onBackground,
// outlineVariant) are filled from its own colours: messageBubble, onSurface, outlineSoft.
// The surface container roles are its surface ladder (see AetherLightColors in Theme.kt).

val aether_light_primary = Color(0xFFAD7BF9)
val aether_light_onPrimary = Color(0xFFFFFFFF)
val aether_light_primaryContainer = Color(0xFFF1E5FF)
val aether_light_onPrimaryContainer = Color(0xFF4D2F8E)
val aether_light_secondary = Color(0xFF4A7B6B)
val aether_light_onSecondary = Color(0xFFFFFFFF)
val aether_light_secondaryContainer = Color(0xFFDDF1E8)
val aether_light_onSecondaryContainer = Color(0xFF1E4A3B)
val aether_light_tertiary = Color(0xFF9A7DF8)
val aether_light_onTertiary = Color(0xFFFFFFFF)
val aether_light_tertiaryContainer = Color(0xFFF0E3FF)
val aether_light_onTertiaryContainer = Color(0xFF4D2F8E)
val aether_light_error = Color(0xFFB43E3E)
val aether_light_onError = Color(0xFFFFFFFF)
val aether_light_errorContainer = Color(0xFFFFE3E3)
val aether_light_onErrorContainer = Color(0xFF5C1414)
val aether_light_background = Color(0xFFFFFFFF)
val aether_light_onBackground = Color(0xFF202123)
val aether_light_surface = Color(0xFFFFFFFF)
val aether_light_onSurface = Color(0xFF202123)
val aether_light_surfaceVariant = Color(0xFFE5E5E5)
val aether_light_onSurfaceVariant = Color(0xFF6B6B6B)
val aether_light_outline = Color(0xFFD9D9D9)
val aether_light_outlineVariant = Color(0xFFE7E7E7)
val aether_light_surfaceLow = Color(0xFFF9F9F9)
val aether_light_surfaceHigh = Color(0xFFF3F3F2)
val aether_light_surfaceHigher = Color(0xFFECECEC)

val aether_dark_primary = Color(0xFFC0AEFF)
val aether_dark_onPrimary = Color(0xFF251448)
val aether_dark_primaryContainer = Color(0xFF3A275F)
val aether_dark_onPrimaryContainer = Color(0xFFF0E9FF)
val aether_dark_secondary = Color(0xFF89C8AF)
val aether_dark_onSecondary = Color(0xFF143126)
val aether_dark_secondaryContainer = Color(0xFF24483A)
val aether_dark_onSecondaryContainer = Color(0xFFDDF6EA)
val aether_dark_tertiary = Color(0xFFD1C2FF)
val aether_dark_onTertiary = Color(0xFF251448)
val aether_dark_tertiaryContainer = Color(0xFF32264A)
val aether_dark_onTertiaryContainer = Color(0xFFF0E9FF)
val aether_dark_error = Color(0xFFFF8E8E)
val aether_dark_onError = Color(0xFF3D0A0A)
val aether_dark_errorContainer = Color(0xFF4A1C1E)
val aether_dark_onErrorContainer = Color(0xFFFFD9DA)
val aether_dark_background = Color(0xFF151619)
val aether_dark_onBackground = Color(0xFFF3F1EC)
val aether_dark_surface = Color(0xFF1C1F23)
val aether_dark_onSurface = Color(0xFFF3F1EC)
val aether_dark_surfaceVariant = Color(0xFF343941)
val aether_dark_onSurfaceVariant = Color(0xFFB9B4AA)
val aether_dark_outline = Color(0xFF4A5059)
val aether_dark_outlineVariant = Color(0xFF3D424A)
val aether_dark_surfaceHigh = Color(0xFF24282D)
val aether_dark_surfaceHigher = Color(0xFF2C3036)

// ── Carbon — Perplexity-inspired: خاکستری تیره + teal ──

val carbon_light_primary = Color(0xFF0099CC)
val carbon_light_onPrimary = Color(0xFFFFFFFF)
val carbon_light_primaryContainer = Color(0xFFE0F4FA)
val carbon_light_onPrimaryContainer = Color(0xFF003344)
val carbon_light_secondary = Color(0xFF636366)
val carbon_light_onSecondary = Color(0xFFFFFFFF)
val carbon_light_secondaryContainer = Color(0xFFE5E5EA)
val carbon_light_onSecondaryContainer = Color(0xFF1C1C1E)
val carbon_light_tertiary = Color(0xFF00897B)
val carbon_light_onTertiary = Color(0xFFFFFFFF)
val carbon_light_tertiaryContainer = Color(0xFFE0F5F2)
val carbon_light_onTertiaryContainer = Color(0xFF003330)
val carbon_light_error = Color(0xFFDC2626)
val carbon_light_onError = Color(0xFFFFFFFF)
val carbon_light_errorContainer = Color(0xFFFEE2E2)
val carbon_light_onErrorContainer = Color(0xFF7F1D1D)
val carbon_light_background = Color(0xFFF2F2F7)
val carbon_light_onBackground = Color(0xFF1C1C1E)
val carbon_light_surface = Color(0xFFFFFFFF)
val carbon_light_onSurface = Color(0xFF1C1C1E)
val carbon_light_surfaceVariant = Color(0xFFE5E5EA)
val carbon_light_onSurfaceVariant = Color(0xFF48484A)
val carbon_light_outline = Color(0xFF8E8E93)
val carbon_light_outlineVariant = Color(0xFFC6C6C8)

val carbon_dark_primary = Color(0xFF0EA5E9)
val carbon_dark_onPrimary = Color(0xFF0C1A22)
val carbon_dark_primaryContainer = Color(0xFF0C4A6E)
val carbon_dark_onPrimaryContainer = Color(0xFFBAE6FD)
val carbon_dark_secondary = Color(0xFF8D8D93)
val carbon_dark_onSecondary = Color(0xFF1C1C1E)
val carbon_dark_secondaryContainer = Color(0xFF2C2C2E)
val carbon_dark_onSecondaryContainer = Color(0xFFF2F2F7)
val carbon_dark_tertiary = Color(0xFF26C6B4)
val carbon_dark_onTertiary = Color(0xFF003330)
val carbon_dark_tertiaryContainer = Color(0xFF004D44)
val carbon_dark_onTertiaryContainer = Color(0xFF80FFF5)
val carbon_dark_error = Color(0xFFF87171)
val carbon_dark_onError = Color(0xFF7F1D1D)
val carbon_dark_errorContainer = Color(0xFF991B1B)
val carbon_dark_onErrorContainer = Color(0xFFFECACA)
val carbon_dark_background = Color(0xFF0D0D0D)
val carbon_dark_onBackground = Color(0xFFF2F2F7)
val carbon_dark_surface = Color(0xFF171717)
val carbon_dark_onSurface = Color(0xFFF2F2F7)
val carbon_dark_surfaceVariant = Color(0xFF212121)
val carbon_dark_onSurfaceVariant = Color(0xFFB4B4B8)
val carbon_dark_outline = Color(0xFF636366)
val carbon_dark_outlineVariant = Color(0xFF3A3A3C)
