package com.hermes.android.ui.theme

import androidx.compose.ui.graphics.Color

// ── Hermes2 Default palette — deep agent console + cyan/violet accents ──

// Light theme
val md_light_primary = Color(0xFF5B4BDB)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFE5DEFF)
val md_light_onPrimaryContainer = Color(0xFF17005C)
val md_light_secondary = Color(0xFF006A78)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFA8EEFF)
val md_light_onSecondaryContainer = Color(0xFF001F26)
val md_light_tertiary = Color(0xFF256A4F)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFA9F2CF)
val md_light_onTertiaryContainer = Color(0xFF002115)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFF8FAFF)
val md_light_onBackground = Color(0xFF171A23)
val md_light_surface = Color(0xFFFFFFFF)
val md_light_onSurface = Color(0xFF171A23)
val md_light_surfaceVariant = Color(0xFFE2E5F2)
val md_light_onSurfaceVariant = Color(0xFF444754)
val md_light_outline = Color(0xFF747785)
val md_light_outlineVariant = Color(0xFFC4C6D4)

// Dark theme
val md_dark_primary = Color(0xFF9B8CFF)
val md_dark_onPrimary = Color(0xFF24008A)
val md_dark_primaryContainer = Color(0xFF3F2CB5)
val md_dark_onPrimaryContainer = Color(0xFFE8DDFF)
val md_dark_secondary = Color(0xFF67D9F2)
val md_dark_onSecondary = Color(0xFF003640)
val md_dark_secondaryContainer = Color(0xFF004E5C)
val md_dark_onSecondaryContainer = Color(0xFFB6EBFF)
val md_dark_tertiary = Color(0xFF7EDDB3)
val md_dark_onTertiary = Color(0xFF003823)
val md_dark_tertiaryContainer = Color(0xFF005137)
val md_dark_onTertiaryContainer = Color(0xFF9AF8CD)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF080D16)
val md_dark_onBackground = Color(0xFFE4E8F4)
val md_dark_surface = Color(0xFF0D1420)
val md_dark_onSurface = Color(0xFFE4E8F4)
val md_dark_surfaceVariant = Color(0xFF202938)
val md_dark_onSurfaceVariant = Color(0xFFC3CAD8)
val md_dark_outline = Color(0xFF8D95A6)
val md_dark_outlineVariant = Color(0xFF3D4658)

// ── آبی چشم (Blue Eye) ──────────────────────────────────────────────────

val blue_light_primary = Color(0xFF1565C0)
val blue_light_onPrimary = Color(0xFFFFFFFF)
val blue_light_primaryContainer = Color(0xFFD1E4FF)
val blue_light_onPrimaryContainer = Color(0xFF001D36)
val blue_light_secondary = Color(0xFF0277BD)
val blue_light_onSecondary = Color(0xFFFFFFFF)
val blue_light_secondaryContainer = Color(0xFFCDE5FF)
val blue_light_onSecondaryContainer = Color(0xFF001D32)
val blue_light_tertiary = Color(0xFF00838F)
val blue_light_onTertiary = Color(0xFFFFFFFF)
val blue_light_tertiaryContainer = Color(0xFFB2EBF2)
val blue_light_onTertiaryContainer = Color(0xFF002022)
val blue_light_error = Color(0xFFBA1A1A)
val blue_light_onError = Color(0xFFFFFFFF)
val blue_light_errorContainer = Color(0xFFFFDAD6)
val blue_light_onErrorContainer = Color(0xFF410002)
val blue_light_background = Color(0xFFF0F4FF)
val blue_light_onBackground = Color(0xFF1A1C1E)
val blue_light_surface = Color(0xFFFAFCFF)
val blue_light_onSurface = Color(0xFF1A1C1E)
val blue_light_surfaceVariant = Color(0xFFDDE3EA)
val blue_light_onSurfaceVariant = Color(0xFF41484D)
val blue_light_outline = Color(0xFF72787E)
val blue_light_outlineVariant = Color(0xFFC1C7CE)

val blue_dark_primary = Color(0xFF82B1FF)
val blue_dark_onPrimary = Color(0xFF003258)
val blue_dark_primaryContainer = Color(0xFF0D47A1)
val blue_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val blue_dark_secondary = Color(0xFF80D8FF)
val blue_dark_onSecondary = Color(0xFF003352)
val blue_dark_secondaryContainer = Color(0xFF004A73)
val blue_dark_onSecondaryContainer = Color(0xFFCDE5FF)
val blue_dark_tertiary = Color(0xFF4DD0E1)
val blue_dark_onTertiary = Color(0xFF00363A)
val blue_dark_tertiaryContainer = Color(0xFF004F54)
val blue_dark_onTertiaryContainer = Color(0xFFB2EBF2)
val blue_dark_error = Color(0xFFFFB4AB)
val blue_dark_onError = Color(0xFF690005)
val blue_dark_errorContainer = Color(0xFF93000A)
val blue_dark_onErrorContainer = Color(0xFFFFDAD6)
val blue_dark_background = Color(0xFF0A1929)
val blue_dark_onBackground = Color(0xFFE1E2E8)
val blue_dark_surface = Color(0xFF0D1F33)
val blue_dark_onSurface = Color(0xFFE1E2E8)
val blue_dark_surfaceVariant = Color(0xFF1A2F44)
val blue_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val blue_dark_outline = Color(0xFF8B9198)
val blue_dark_outlineVariant = Color(0xFF41484D)

// ── کلود (Claude-style terracotta/warm) ─────────────────────────────────

val claude_light_primary = Color(0xFFD97706)
val claude_light_onPrimary = Color(0xFFFFFFFF)
val claude_light_primaryContainer = Color(0xFFFFE0B2)
val claude_light_onPrimaryContainer = Color(0xFF3E2800)
val claude_light_secondary = Color(0xFFBF360C)
val claude_light_onSecondary = Color(0xFFFFFFFF)
val claude_light_secondaryContainer = Color(0xFFFFCCBC)
val claude_light_onSecondaryContainer = Color(0xFF3B0A00)
val claude_light_tertiary = Color(0xFF6D4C41)
val claude_light_onTertiary = Color(0xFFFFFFFF)
val claude_light_tertiaryContainer = Color(0xFFD7CCC8)
val claude_light_onTertiaryContainer = Color(0xFF2C1A10)
val claude_light_error = Color(0xFFBA1A1A)
val claude_light_onError = Color(0xFFFFFFFF)
val claude_light_errorContainer = Color(0xFFFFDAD6)
val claude_light_onErrorContainer = Color(0xFF410002)
val claude_light_background = Color(0xFFFFF8F0)
val claude_light_onBackground = Color(0xFF1F1B16)
val claude_light_surface = Color(0xFFFFFBF7)
val claude_light_onSurface = Color(0xFF1F1B16)
val claude_light_surfaceVariant = Color(0xFFF0E6D8)
val claude_light_onSurfaceVariant = Color(0xFF4F4539)
val claude_light_outline = Color(0xFF817567)
val claude_light_outlineVariant = Color(0xFFD2C4B4)

val claude_dark_primary = Color(0xFFFFB74D)
val claude_dark_onPrimary = Color(0xFF4E2A00)
val claude_dark_primaryContainer = Color(0xFF9E6A00)
val claude_dark_onPrimaryContainer = Color(0xFFFFE0B2)
val claude_dark_secondary = Color(0xFFFF8A65)
val claude_dark_onSecondary = Color(0xFF5F1600)
val claude_dark_secondaryContainer = Color(0xFF8B2500)
val claude_dark_onSecondaryContainer = Color(0xFFFFCCBC)
val claude_dark_tertiary = Color(0xFFBCAAA4)
val claude_dark_onTertiary = Color(0xFF3E2B22)
val claude_dark_tertiaryContainer = Color(0xFF5D4037)
val claude_dark_onTertiaryContainer = Color(0xFFD7CCC8)
val claude_dark_error = Color(0xFFFFB4AB)
val claude_dark_onError = Color(0xFF690005)
val claude_dark_errorContainer = Color(0xFF93000A)
val claude_dark_onErrorContainer = Color(0xFFFFDAD6)
val claude_dark_background = Color(0xFF1A1410)
val claude_dark_onBackground = Color(0xFFEDE0D4)
val claude_dark_surface = Color(0xFF211A14)
val claude_dark_onSurface = Color(0xFFEDE0D4)
val claude_dark_surfaceVariant = Color(0xFF3A2F24)
val claude_dark_onSurfaceVariant = Color(0xFFD2C4B4)
val claude_dark_outline = Color(0xFF9B8E80)
val claude_dark_outlineVariant = Color(0xFF4F4539)
