package com.hermes.android.runtime.termux

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Generates the bash script that installs Hermes inside Termux.
 *
 * Hermes ships Termux as a signed APT package (aarch64 only); its install.sh
 * stops on Termux with "pkg install hermes-agent". The script follows
 * hermes-agent.nousresearch.com/docs/getting-started/termux:
 * 1. Checks the Termux architecture is aarch64
 * 2. Installs curl and gnupg
 * 3. Downloads the repository key, checks its fingerprint, adds the repository
 *    (stable when published, else canary — stable is 404 as of 2026-10-02)
 * 4. Moves aside any hermes launcher the package does not own (its postinst
 *    refuses to replace one)
 * 5. apt-get install hermes-agent
 * 6. Reports hermes --version, hermes doctor and the package's Python version
 * Each step reports progress via am broadcast.
 *
 * ## Robustness (survives app crash / screen off / network drop)
 * The script runs inside Termux, independent of this app's process, and is
 * hardened so a flaky phone can't corrupt the install:
 * - **Persistent state** — every progress/error/complete update is also
 *   written atomically to `~/.hermes/install.state`. If the app dies, the
 *   state survives; [generateStateResyncScript] re-broadcasts it on demand.
 * - **Wake lock** — `termux-wake-lock` (when available) stops Android from
 *   freezing Termux mid-compile with the screen off.
 * - **Single-instance lock** — a PID file prevents two installers racing.
 * - **Retries** — each apt step gets 3 attempts with a network-wait between
 *   them; apt continues a partial download on the next attempt.
 * - **Interrupt detection** — an EXIT trap marks the state `failed` if the
 *   script dies while still `running`, so the app can offer Resume.
 *
 * Reference: ADR-007
 */
@Singleton
class TermuxInstaller @Inject constructor(
    @ApplicationContext private val context: Context,
) {

    enum class BroadcastAction(val action: String) {
        PROGRESS("com.hermes.android.INSTALL_PROGRESS"),
        COMPLETE("com.hermes.android.INSTALL_COMPLETE"),
        ERROR("com.hermes.android.INSTALL_ERROR"),
    }

    /**
     * The pure bash script body that performs the Hermes install inside Termux.
     *
     * This is the canonical install script. It is sent to Termux via
     * [TermuxCommandExecutor.executeBackgroundScript] — NOT via copy/paste.
     * Kept as a separate method so the script can be unit-tested and reused
     * by both the automated path and (as a fallback) the legacy copy/paste
     * instructions screen.
     */
    fun generateInstallScript(): String {
        val receiver = context.packageName
        return buildString {
            appendLine("# Hermes Agent — Android install script")
            appendLine("# Generated by Hermes2 app. Executed automatically via RUN_COMMAND.")
            appendLine("# Installs Hermes's signed Termux APT package (pkg install hermes-agent)")
            appendLine("set -e")
            appendLine("set -o pipefail")
            appendLine()
            appendLine("RECEIVER=\"$receiver\"")
            appendLine("PROGRESS_ACTION=\"${BroadcastAction.PROGRESS.action}\"")
            appendLine("COMPLETE_ACTION=\"${BroadcastAction.COMPLETE.action}\"")
            appendLine("ERROR_ACTION=\"${BroadcastAction.ERROR.action}\"")
            appendLine("PREFIX=\"\${PREFIX:-/data/data/com.termux/files/usr}\"")
            appendLine("REPO_BASE=\"https://hermes-assets.nousresearch.com/releases/termux\"")
            appendLine("KEY_FINGERPRINT=\"C572B5FDD1A29CCFA9A912B6840B0848E139156D\"")
            appendLine("STATE_FILE=\"\$HOME/.hermes/install.state\"")
            appendLine("LOCK_FILE=\"\$HOME/.hermes/.install.pid\"")
            appendLine("mkdir -p \"\$HOME/.hermes/logs\"")
            appendLine()
            appendLine("# Persistent state: survives app crash/kill. Written atomically so a")
            appendLine("# reader never sees a half-written file. Read back by the app via the")
            appendLine("# state-resync script whenever the setup screen opens.")
            appendLine("write_state() {")
            appendLine("    printf 'status=%s\\nstage=%s\\npercent=%s\\nmessage=%s\\nts=%s\\n' \\")
            appendLine("        \"\$1\" \"\$2\" \"\$3\" \"\$4\" \"\$(date +%s)\" > \"\$STATE_FILE.tmp\" 2>/dev/null \\")
            appendLine("        && mv \"\$STATE_FILE.tmp\" \"\$STATE_FILE\" 2>/dev/null || true")
            appendLine("}")
            appendLine()
            appendLine("report_progress() {")
            appendLine("    local stage=\"\$1\" message=\"\$2\" percent=\"\$3\"")
            appendLine("    write_state running \"\$stage\" \"\$percent\" \"\$message\"")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("        --es stage \"\$stage\" \\")
            appendLine("        --es message \"\$message\" \\")
            appendLine("        --ei percent \"\$percent\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("report_complete() {")
            appendLine("    write_state done complete 100 \"Installation complete\"")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$COMPLETE_ACTION\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("report_error() {")
            appendLine("    local message=\"\$1\"")
            appendLine("    write_state failed \"\${STAGE:-unknown}\" \"\${PERCENT:-0}\" \"\$message\"")
            appendLine("    am broadcast -p \"\$RECEIVER\" -a \"\$ERROR_ACTION\" --es message \"\$message\" >/dev/null 2>&1 || true")
            appendLine("}")
            appendLine()
            appendLine("# Single-instance lock: a second Install tap while one is running only")
            appendLine("# re-announces progress instead of corrupting the live install.")
            appendLine("if [ -f \"\$LOCK_FILE\" ] && kill -0 \"\$(cat \"\$LOCK_FILE\" 2>/dev/null)\" 2>/dev/null; then")
            appendLine("    report_progress \"already_running\" \"An install is already running — attaching to its progress.\" 1")
            appendLine("    exit 0")
            appendLine("fi")
            appendLine("echo \$\$ > \"\$LOCK_FILE\"")
            appendLine()
            appendLine("# Keep the CPU awake during the long package download. Without this,")
            appendLine("# Android may freeze Termux when the screen turns off, breaking the")
            appendLine("# install halfway. termux-api may not be installed — best effort.")
            appendLine("command -v termux-wake-lock >/dev/null 2>&1 && termux-wake-lock || true")
            appendLine()
            appendLine("cleanup() {")
            appendLine("    command -v termux-wake-unlock >/dev/null 2>&1 && termux-wake-unlock || true")
            appendLine("    rm -f \"\$LOCK_FILE\"")
            appendLine("    # Detect an interrupted install (Termux killed, phone rebooted...):")
            appendLine("    # if we exit while the state still says running, mark it failed so")
            appendLine("    # the app can offer Resume instead of showing a frozen progress bar.")
            appendLine("    if grep -q '^status=running' \"\$STATE_FILE\" 2>/dev/null; then")
            appendLine("        write_state failed \"\${STAGE:-unknown}\" \"\${PERCENT:-0}\" \"Install interrupted at stage \${STAGE:-unknown}. Tap Install again to resume — apt continues the download where it stopped.\"")
            appendLine("    fi")
            appendLine("}")
            appendLine("trap cleanup EXIT")
            appendLine("trap 'report_error \"Install failed at stage: \$STAGE — tap Install again to resume. Log: ~/.hermes/logs/install.log\"' ERR")
            appendLine()
            appendLine("# Wait up to ~2 minutes for connectivity before declaring a network")
            appendLine("# failure — mobile networks drop and recover all the time.")
            appendLine("wait_for_network() {")
            appendLine("    local i=1")
            appendLine("    while [ \$i -le 12 ]; do")
            appendLine("        command -v curl >/dev/null 2>&1 || { sleep 10; return 0; }")
            appendLine("        curl -sI --max-time 8 \"https://hermes-assets.nousresearch.com\" >/dev/null 2>&1 && return 0")
            appendLine("        report_progress \"\${STAGE:-network}\" \"Waiting for network (\$i/12)...\" \"\${PERCENT:-5}\"")
            appendLine("        sleep 10")
            appendLine("        i=\$((i + 1))")
            appendLine("    done")
            appendLine("    return 1")
            appendLine("}")
            appendLine()
            appendLine("# Hermes ships Termux as a signed APT package; its install.sh refuses to run")
            appendLine("# in Termux. Steps follow hermes-agent.nousresearch.com/docs/getting-started/termux")
            appendLine("log() { echo \"\$1\" | tee -a \"\$HOME/.hermes/logs/install.log\"; }")
            appendLine("apt_quiet() {")
            appendLine("    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold \"\$@\" 2>&1 | tee -a \"\$HOME/.hermes/logs/install.log\"")
            appendLine("}")
            appendLine("# Phones drop off the network mid-download, and a pkg run in Termux holds the")
            appendLine("# dpkg lock: each apt step gets 3 attempts.")
            appendLine("apt_retry() {")
            appendLine("    local attempt=1")
            appendLine("    while ! apt_quiet \"\$@\"; do")
            appendLine("        if [ \$attempt -ge 3 ]; then return 1; fi")
            appendLine("        attempt=\$((attempt + 1))")
            appendLine("        report_progress \"\$STAGE\" \"apt-get \$1 failed — retrying (\$attempt/3)...\" \"\$PERCENT\"")
            appendLine("        wait_for_network || true")
            appendLine("        sleep 5")
            appendLine("    done")
            appendLine("}")
            appendLine()
            appendLine("STAGE=\"check\"")
            appendLine("PERCENT=3")
            appendLine("report_progress \"\$STAGE\" \"Checking Termux...\" 3")
            appendLine("TERMUX_ARCH=\$(dpkg --print-architecture 2>/dev/null || uname -m)")
            appendLine("if [ \"\$TERMUX_ARCH\" != \"aarch64\" ]; then")
            appendLine("    report_error \"Hermes's Termux package is built for 64-bit ARM (aarch64) only; this Termux is \$TERMUX_ARCH.\"")
            appendLine("    exit 1")
            appendLine("fi")
            appendLine()
            appendLine("STAGE=\"tools\"")
            appendLine("PERCENT=10")
            appendLine("report_progress \"\$STAGE\" \"Installing curl and gnupg...\" 10")
            appendLine("if ! command -v curl >/dev/null 2>&1 || ! command -v gpg >/dev/null 2>&1; then")
            appendLine("    apt_retry update")
            appendLine("    apt_retry install curl gnupg")
            appendLine("fi")
            appendLine()
            appendLine("STAGE=\"repository\"")
            appendLine("PERCENT=20")
            appendLine("report_progress \"\$STAGE\" \"Adding the Hermes package repository...\" 20")
            appendLine("wait_for_network || true")
            appendLine("# No stable build is published yet (its key and Release are 404); canary is")
            appendLine("# the only channel with a package. Stable is taken as soon as it appears.")
            appendLine("CHANNEL=stable")
            appendLine("if ! curl -fsI --max-time 20 \"\$REPO_BASE/stable/dists/hermes-stable/Release\" >/dev/null 2>&1; then")
            appendLine("    CHANNEL=canary")
            appendLine("fi")
            appendLine("KEYRING=\"\$PREFIX/etc/apt/keyrings/hermes-agent.asc\"")
            appendLine("mkdir -p \"\$PREFIX/etc/apt/keyrings\" \"\$PREFIX/etc/apt/sources.list.d\"")
            appendLine("curl -fsSL --retry 3 \"\$REPO_BASE/\$CHANNEL/key.asc\" -o \"\$KEYRING.tmp\"")
            appendLine("FPR=\$(gpg --show-keys --with-colons \"\$KEYRING.tmp\" 2>/dev/null | awk -F: '/^fpr:/ {print \$10; exit}' || true)")
            appendLine("if [ \"\$FPR\" != \"\$KEY_FINGERPRINT\" ]; then")
            appendLine("    rm -f \"\$KEYRING.tmp\"")
            appendLine("    report_error \"The Hermes repository key has an unexpected fingerprint (\${FPR:-none}). Install stopped.\"")
            appendLine("    exit 1")
            appendLine("fi")
            appendLine("mv -f \"\$KEYRING.tmp\" \"\$KEYRING\"")
            appendLine("printf '%s\\n' \"deb [signed-by=\$KEYRING] \$REPO_BASE/\$CHANNEL hermes-\$CHANNEL main\" > \"\$PREFIX/etc/apt/sources.list.d/hermes-agent.list\"")
            appendLine("log \"Hermes repository channel: \$CHANNEL\"")
            appendLine()
            appendLine("STAGE=\"launchers\"")
            appendLine("PERCENT=30")
            appendLine("# The package refuses to replace a hermes launcher it does not own, such as")
            appendLine("# the one an older install.sh/pip install left in \$PREFIX/bin.")
            appendLine("for name in hermes hermes-agent hermes-acp; do")
            appendLine("    link=\"\$PREFIX/bin/\$name\"")
            appendLine("    if [ -L \"\$link\" ] && [ \"\$(readlink \"\$link\")\" = \"../lib/hermes-agent/bin/\$name\" ]; then")
            appendLine("        continue")
            appendLine("    fi")
            appendLine("    if [ -e \"\$link\" ] || [ -L \"\$link\" ]; then")
            appendLine("        log \"Moving old launcher aside: \$link -> \$link.old\"")
            appendLine("        mv -f \"\$link\" \"\$link.old\"")
            appendLine("    fi")
            appendLine("done")
            appendLine()
            appendLine("STAGE=\"package\"")
            appendLine("PERCENT=40")
            appendLine("report_progress \"\$STAGE\" \"Downloading and installing Hermes (\$CHANNEL, ~160 MB)...\" 40")
            appendLine("apt_retry update")
            appendLine("apt_retry install hermes-agent")
            appendLine()
            appendLine("# Verify: hermes --version (Fix S2F05)")
            appendLine("STAGE=\"verify_version\"")
            appendLine("PERCENT=92")
            appendLine("report_progress \"\$STAGE\" \"Checking hermes --version...\" 92")
            appendLine("HERMES_CMD=\"\$PREFIX/bin/hermes\"")
            appendLine("if ! [ -x \"\$HERMES_CMD\" ]; then")
            appendLine("    report_error \"Hermes command not found after install. Expected \$HERMES_CMD. Check \$HOME/.hermes/logs/install.log\"")
            appendLine("    exit 1")
            appendLine("fi")
            appendLine("HERMES_VERSION=\$(\"\$HERMES_CMD\" --version 2>&1 | head -n 1 || true)")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"verify_version\" \\")
            appendLine("    --es message \"Hermes version: \$HERMES_VERSION\" \\")
            appendLine("    --ei percent 94 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("# Verify: hermes doctor (Fix S2F06)")
            appendLine("STAGE=\"verify_doctor\"")
            appendLine("PERCENT=96")
            appendLine("report_progress \"\$STAGE\" \"Running hermes doctor...\" 96")
            appendLine("DOCTOR_OUTPUT=\$(\"\$HERMES_CMD\" doctor 2>&1 || echo \"doctor ready\")")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"verify_doctor\" \\")
            appendLine("    --es message \"Doctor: \$DOCTOR_OUTPUT\" \\")
            appendLine("    --ei percent 98 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("# Detect Python version (Fix S2F01)")
            appendLine("PYTHON_VERSION=\$(\"\$PREFIX/lib/hermes-agent/venv/bin/python\" --version 2>&1 || echo \"unknown\")")
            appendLine("am broadcast -p \"\$RECEIVER\" -a \"\$PROGRESS_ACTION\" \\")
            appendLine("    --es stage \"python_version\" \\")
            appendLine("    --es message \"Python: \$PYTHON_VERSION\" \\")
            appendLine("    --ei percent 99 >/dev/null 2>&1 || true")
            appendLine()
            appendLine("STAGE=\"complete\"")
            appendLine("PERCENT=100")
            appendLine("report_progress \"\$STAGE\" \"Installation complete! Hermes: \$HERMES_VERSION, Python: \$PYTHON_VERSION\" 100")
            appendLine("report_complete")
        }
    }

    /**
     * Small script that re-broadcasts the persisted install state to the app.
     *
     * Fired when the setup screen opens (see TermuxBridge.detect). If the app
     * crashed or was closed mid-install, this restores the UI from
     * `~/.hermes/install.state` using the SAME broadcast actions the live
     * installer uses — no extra receiver logic needed. It also detects a
     * silently-dead installer (state says running but the PID is gone) and
     * converts it to a resumable error.
     */
    fun generateStateResyncScript(): String {
        val receiver = context.packageName
        return buildString {
            appendLine("STATE_FILE=\"\$HOME/.hermes/install.state\"")
            appendLine("LOCK_FILE=\"\$HOME/.hermes/.install.pid\"")
            appendLine("[ -f \"\$STATE_FILE\" ] || exit 0")
            appendLine("status=\$(sed -n 's/^status=//p' \"\$STATE_FILE\" | head -1)")
            appendLine("stage=\$(sed -n 's/^stage=//p' \"\$STATE_FILE\" | head -1)")
            appendLine("percent=\$(sed -n 's/^percent=//p' \"\$STATE_FILE\" | head -1)")
            appendLine("message=\$(sed -n 's/^message=//p' \"\$STATE_FILE\" | head -1)")
            appendLine("case \"\$status\" in")
            appendLine("  done)")
            appendLine("    am broadcast -p \"$receiver\" -a \"${BroadcastAction.COMPLETE.action}\" >/dev/null 2>&1 || true ;;")
            appendLine("  failed)")
            appendLine("    am broadcast -p \"$receiver\" -a \"${BroadcastAction.ERROR.action}\" --es message \"\$message\" >/dev/null 2>&1 || true ;;")
            appendLine("  running)")
            appendLine("    if [ -f \"\$LOCK_FILE\" ] && kill -0 \"\$(cat \"\$LOCK_FILE\" 2>/dev/null)\" 2>/dev/null; then")
            appendLine("        am broadcast -p \"$receiver\" -a \"${BroadcastAction.PROGRESS.action}\" \\")
            appendLine("            --es stage \"\$stage\" --es message \"\$message\" --ei percent \"\${percent:-0}\" >/dev/null 2>&1 || true")
            appendLine("    else")
            appendLine("        printf 'status=failed\\nstage=%s\\npercent=%s\\nmessage=%s\\nts=%s\\n' \"\$stage\" \"\${percent:-0}\" \"Install was interrupted at stage \$stage. Tap Install to resume.\" \"\$(date +%s)\" > \"\$STATE_FILE\" 2>/dev/null || true")
            appendLine("        am broadcast -p \"$receiver\" -a \"${BroadcastAction.ERROR.action}\" \\")
            appendLine("            --es message \"Install was interrupted at stage \$stage. Tap Install to resume — apt continues the download where it stopped.\" >/dev/null 2>&1 || true")
            appendLine("    fi ;;")
            appendLine("esac")
        }
    }

    /**
     * Legacy entry point preserved for the fallback "copy/paste" instructions
     * screen. The automated path uses [generateInstallScript] instead.
     */
    fun generateInstallCommand(): String = generateInstallScript()

}
